apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd #NS where the gitlab is installed
spec:
  commonName: argocd.abhinavm.local  # Your GitLab domain or subdomain
  secretName: argocd-tls-secret  # The secret where the certificate will be stored. will be automatically created by cert-manager.
  issuerRef:
    name: selfsigned-issuer  # The issuer for signing the certificate
    kind: ClusterIssuer
  dnsNames:
    - argocd.abhinavm.local
