apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-ceph-block
  csi:
    driver: rook-ceph.rbd.csi.ceph.com
    volumeHandle: gitlab-pv-handle
