apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: homelabpool
  namespace: rook-ceph # namespace:cluster
spec:
  failureDomain: host
  replicated:
    size: 2
    requireSafeReplicaSize: false
