apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab
  namespace: argocd
spec:
  destination:
    namespace: gitlab
    server: https://kubernetes.default.svc
  source:
    path: infra/gitlab
    repoURL: https://github.com/abhinav1015/Devops-Homelab
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      createNamespace: true
  ignoreDifferences:
    - group: ''
      kind: Secret
      name: gitlab-tls-secret
      namespace: gitlab
      jsonPointers:
        - /data
